/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['selector', '[data-theme="dark"]'],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'var(--inkblot-color-accent-citron-50)',
          100: 'var(--inkblot-color-accent-citron-100)',
          200: 'var(--inkblot-color-accent-citron-200)',
          300: 'var(--inkblot-color-accent-citron-300)',
          400: 'var(--inkblot-color-accent-citron-400)',
          500: 'var(--inkblot-color-accent-citron-500)',
          600: 'var(--inkblot-color-accent-citron-600)',
          700: 'var(--inkblot-color-accent-citron-700)',
          800: 'var(--inkblot-color-accent-citron-800)',
          900: 'var(--inkblot-color-accent-citron-900)',
        },
        neutral: {
          50: 'var(--inkblot-color-neutral-gray-50)',
          100: 'var(--inkblot-color-neutral-gray-100)',
          200: 'var(--inkblot-color-neutral-gray-200)',
          300: 'var(--inkblot-color-neutral-gray-300)',
          400: 'var(--inkblot-color-neutral-gray-400)',
          500: 'var(--inkblot-color-neutral-gray-500)',
          600: 'var(--inkblot-color-neutral-gray-600)',
          700: 'var(--inkblot-color-neutral-gray-700)',
          800: 'var(--inkblot-color-neutral-gray-800)',
          900: 'var(--inkblot-color-neutral-gray-900)',
          950: 'var(--inkblot-color-neutral-gray-950)',
          white: 'var(--inkblot-color-neutral-white)',
        },
        success: {
          light: 'var(--inkblot-color-semantic-success-light)',
          DEFAULT: 'var(--inkblot-color-semantic-success-main)',
          dark: 'var(--inkblot-color-semantic-success-dark)',
        },
        warning: {
          light: 'var(--inkblot-color-semantic-warning-light)',
          DEFAULT: 'var(--inkblot-color-semantic-warning-main)',
          dark: 'var(--inkblot-color-semantic-warning-dark)',
        },
        error: {
          light: 'var(--inkblot-color-semantic-error-light)',
          DEFAULT: 'var(--inkblot-color-semantic-error-main)',
          dark: 'var(--inkblot-color-semantic-error-dark)',
        },
      },
      spacing: {
        0: 'var(--inkblot-spacing-0)',
        1: 'var(--inkblot-spacing-1)',
        2: 'var(--inkblot-spacing-2)',
        3: 'var(--inkblot-spacing-3)',
        4: 'var(--inkblot-spacing-4)',
        5: 'var(--inkblot-spacing-5)',
        6: 'var(--inkblot-spacing-6)',
        8: 'var(--inkblot-spacing-8)',
        10: 'var(--inkblot-spacing-10)',
        12: 'var(--inkblot-spacing-12)',
        16: 'var(--inkblot-spacing-16)',
        20: 'var(--inkblot-spacing-20)',
        24: 'var(--inkblot-spacing-24)',
        32: 'var(--inkblot-spacing-32)',
      },
      borderRadius: {
        none: 'var(--inkblot-radius-none)',
        sm: 'var(--inkblot-radius-sm)',
        DEFAULT: 'var(--inkblot-radius-md)',
        md: 'var(--inkblot-radius-md)',
        lg: 'var(--inkblot-radius-lg)',
        xl: 'var(--inkblot-radius-xl)',
        '2xl': 'var(--inkblot-radius-2xl)',
        full: 'var(--inkblot-radius-full)',
      },
      fontFamily: {
        sans: ['Outfit', 'Inter', 'SF Pro Text', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        display: ['Outfit', 'SF Pro Display', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
      },
      fontSize: {
        xs: 'var(--inkblot-typography-font-size-xs)',
        sm: 'var(--inkblot-typography-font-size-sm)',
        base: 'var(--inkblot-typography-font-size-base)',
        lg: 'var(--inkblot-typography-font-size-lg)',
        xl: 'var(--inkblot-typography-font-size-xl)',
        '2xl': 'var(--inkblot-typography-font-size-2xl)',
        '3xl': 'var(--inkblot-typography-font-size-3xl)',
        '4xl': 'var(--inkblot-typography-font-size-4xl)',
        '5xl': 'var(--inkblot-typography-font-size-5xl)',
      },
      fontWeight: {
        normal: 'var(--inkblot-typography-font-weight-regular)',
        medium: 'var(--inkblot-typography-font-weight-medium)',
        semibold: 'var(--inkblot-typography-font-weight-semibold)',
        bold: 'var(--inkblot-typography-font-weight-bold)',
      },
      boxShadow: {
        xs: 'var(--inkblot-shadow-xs)',
        sm: 'var(--inkblot-shadow-sm)',
        DEFAULT: 'var(--inkblot-shadow-md)',
        md: 'var(--inkblot-shadow-md)',
        lg: 'var(--inkblot-shadow-lg)',
        xl: 'var(--inkblot-shadow-xl)',
      },
      transitionDuration: {
        instant: 'var(--inkblot-duration-instant)',
        fast: 'var(--inkblot-duration-fast)',
        normal: 'var(--inkblot-duration-normal)',
        slow: 'var(--inkblot-duration-slow)',
        slower: 'var(--inkblot-duration-slower)',
      },
      zIndex: {
        dropdown: 'var(--inkblot-z-index-dropdown)',
        sticky: 'var(--inkblot-z-index-sticky)',
        overlay: 'var(--inkblot-z-index-overlay)',
        modal: 'var(--inkblot-z-index-modal)',
        popover: 'var(--inkblot-z-index-popover)',
        toast: 'var(--inkblot-z-index-toast)',
      },
    },
  },
  plugins: [],
}
