#!/usr/bin/env node
/**
 * Inject client config for citron-identity (Vite).
 * Writes .env.local, src/config/client-config.generated.ts, .hillcode-client
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");

const CLIENTS = {
  citron: { displayName: "Citron", productName: "Citron Identity" },
  inkid: { displayName: "InkID", productName: "InkID Auth Portal" },
};

const clientId = process.argv[2] ?? "citron";
const cfg = CLIENTS[clientId];

if (!cfg) {
  console.error(`inject: unknown client "${clientId}" (use: citron | inkid)`);
  process.exit(1);
}

writeFileSync(
  join(repoRoot, ".env.local"),
  [
    "# Generated by devtools/inject.mjs",
    `VITE_CLIENT=${clientId}`,
    "",
  ].join("\n"),
  "utf8"
);

writeFileSync(join(repoRoot, ".hillcode-client"), `${clientId}\n`, "utf8");

const genDir = join(repoRoot, "src", "config");
mkdirSync(genDir, { recursive: true });
writeFileSync(
  join(genDir, "client-config.generated.ts"),
  `/** Auto-generated by devtools/inject.mjs — do not edit */
export const GENERATED_CLIENT_ID = '${clientId}' as const;
export const GENERATED_DISPLAY_NAME = '${cfg.displayName}';
export const GENERATED_PRODUCT_NAME = '${cfg.productName}';
`,
  "utf8"
);

console.error(`inject: ${clientId} (${cfg.productName})`);
