/** Auto-generated by devtools/inject.mjs — do not edit */
export const GENERATED_CLIENT_ID = 'citron' as const;
export const GENERATED_DISPLAY_NAME = 'Citron';
export const GENERATED_PRODUCT_NAME = 'Citron Identity';
